### ISSUE TITLE
Seems to crash every time machine is unlocked after most recent batch of updates

### ISSUE THREAD

**Issue by axfelix** [rgcjonas/gnome-shell-extension-appindicator#58]
Running a fairly standard Gnome 3.18 install on Arch... this extension used to cleanly survive suspend/resume/unlock, now it doesn't and I need to restart the shell.

**Comment by rgcjonas** [comment]
I actually thought I fixed that one. It certainly works on Gnome 3.16, but my 3.18 VM didn't feel like booting up today, so I couldn't test it there (I'll try and hopefully get that sorted out this week).

Do you have any logs containing error messages etc. related to the crash? Please post them.

**Comment by axfelix** [comment]
I actually tried reverting yesterday to before your most recent batch of changes and it didn't fix the issue, so it's likely 3.18 related after all. Sorry about that. I'm happy to get logs but not familiar with how to do so in this case.

**Comment by rgcjonas** [comment]
The Shell writes diagnostic messages to stderr, which (via gnome-session) should end up in the journal, which you can view via `journalctl(1)`.

For the brute-force solution, you could just upload every journal entry (`jounalctl --user`) that is created while you reproduce the issue.

Fixing Gnome 3.18 compatibility is a priority. After all, I saw it working in my testing and people stated that the old version worked, too. Have you enabled any other extensions? Try disabling them. The chance of colliding with other extensions is very small, but it has happened in the past. We might also have tripped the occasional gjs or gnome-shell bug that had not been present in the version I tested against.

**Comment by axfelix** [comment]
I'm also running https://extensions.gnome.org/extension/746/chat-status/ as well as TopIcons (as a fallback for when old tray apps don't seem to support AppIndicator on Gnome 3, such as Dropbox, though I can't figure out why libappindicator isn't kicking in for it since it seems to work under Ubuntu's desktop), though I've tested disabling these and they don't seem to effect the AppIndicator crashes.

Is there an easy way to redirect gnome shell stderr to a file? I'm having a hard time parsing much out of journalctl with all the miscellaneous dmesg output it contains, particularly as this is only reliably triggered on suspend/resume.

**Comment by rgcjonas** [comment]
So standard lock/unlock doesn't trigger it? Only suspend/resume? That's a new piece of information.

Try `journalctl _PID=$(pgrep gnome-session)`

**Comment by axfelix** [comment]
[axfelix@nixon offlineimap]$ journalctl _PID=$(pgrep gnome-session)
Failed to add match '1871': Invalid argument

Standard lock/unlock does trigger it, just checked.

**Comment by axfelix** [comment]
Oh, and this does return results, but only up to June? looks like my journal is full or something:

[axfelix@nixon offlineimap]$ pgrep gnome-session
525
1871
[axfelix@nixon offlineimap]$ journalctl _PID=$525
-- No entries --
[axfelix@nixon offlineimap]$ journalctl _PID=$1871

**Comment by axfelix** [comment]
Okay, managed to clean up old journal entries and get actual output for you:

Oct 21 15:54:29 nixon gnome-session[1871]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Oct 21 15:54:32 nixon gnome-session[1871]: Gjs-Message: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
Oct 21 15:54:32 nixon gnome-session[1871]: Gjs-Message: JS WARNING: [/home/axfelix/.local/share/gnome-shell/extensions/chatstatus@zeten30.gmail.com/extension.js  116]: variable label redeclares argument
Oct 21 15:54:32 nixon gnome-session[1871]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Numix-Frost-Light/gnome-shell/gnome-shell.css
Oct 21 15:54:33 nixon gnome-session[1871]: ** (gnome-shell:21074): CRITICAL **: nma_mobile_providers_database_lookup_cdma_sid: assertion 'sid > 0' failed
Oct 21 15:54:43 nixon gnome-session[1871]: Gjs-Message: JS LOG: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem:1.46476/org/kde/statusnotifieritem/1
Oct 21 15:55:16 nixon gnome-session[1871]: Gjs-Message: JS LOG: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.46500/org/kde/statusnotifieritem/1
Oct 21 15:56:08 nixon gnome-session[1871]: Gjs-Message: JS LOG: Extension "appindicatorsupport@rgcjonas.gmail.com" had error: ReferenceError: detectExtensionsID is not defined
Oct 21 15:56:08 nixon gnome-session[1871]: [23772:23794:1021/155608:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -106
Oct 21 15:56:26 nixon gnome-session[1871]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Numix-Frost-Light/gnome-shell/gnome-shell.css
r session.
Oct 21 15:56:34 nixon gnome-session[1871]: Created new window in existing browser session
Oct 21 15:57:01 nixon gnome-session[1871]: ** (gnome-shell:21074): CRITICAL **: nma_mobile_providers_database_lookup_cdma_sid: assertion 'sid > 0' failed

that's everything after a recent lock/unlock (which also triggers suspend/resume on this machine because it's a Venue 11 Pro convertible tablet and does weird ACPI stuff when the display is turned off). looks like detectExtensionsID is a problem in 3.18?

**Comment by rgcjonas** [comment]
The `detectExtensionsID` bug has actually been fixed ages ago and got released as v17. Sadly, the crucial commit didn't make it into master because I fucked up (forgot?) `git push`.

I'm very sorry.

Thank you for reporting this bug and taking the time to provide the log. Feel free to reopen if the issue still persists after upgrading to b8e5545.

**Comment by axfelix** [comment]
Yup, fixed! I bet I know why I started encountering it when I updated to 3.18; I decided to switch from the version installed by extensions.gnome.org to the git version at the same time so I wouldn't have to keep updating the compatible versions in metadata.json, and I didn't expect that git would be behind the published version. Glad we sorted that out! I was afraid of what it'd mean if Gnome were deprecating APIs so aggressively that simple extensions would have to be continually updated every six months to avoid breakage...
